Homework 5
OlgaPoddubnaia/OlgaPoddubnaia pull request #5
Opened 2021-01-14 17:18 UTC by OlgaPoddubnaia

2021-01-17 22:45 UTC, DmitryKhodakovsky requested changes

2021-01-17 22:45 UTC, DmitryKhodakovsky commented on pom.xml
> +        </dependency>
Why do you need these drivers as separate dependencies?

2021-01-17 22:45 UTC, DmitryKhodakovsky commented on src/test/java/hw5/steps/ThenStepDef.java
> +        softAssert.assertAll();
What is the reason of using softAssertions here?

2021-01-17 22:45 UTC, DmitryKhodakovsky commented on src/test/java/hw5/steps/ThenStepDef.java
> +    @Then("6 Number Type Dropdowns should be displayed on Users Table on User Table Page")
Why is number of dropdown hardcoded?

2021-01-17 22:45 UTC, DmitryKhodakovsky commented on src/test/java/hw5/steps/ThenStepDef.java
> +    @Then("6 Usernames should be displayed on Users Table on User Table Page")
Why is number of the users hardcoded?

2021-01-17 22:45 UTC, DmitryKhodakovsky commented on src/test/java/hw5/steps/ThenStepDef.java
> +    @Then("1 log row has \"Vip: condition changed to true\" text in log section")
Why is expected text of the log row is hardcoded?

2021-01-17 22:45 UTC, DmitryKhodakovsky commented on src/test/java/hw5/steps/WhenStepDef.java
> +    @When("I select water, wind checkboxes")
What will you actions if you need select more checkboxes?

2021-01-17 22:45 UTC, DmitryKhodakovsky commented on src/test/resources/hw5/Cucumber_Exercise_2.feature
> +    And I click on "User Table" button in Service dropdown
`Service` and `User Table` should be as parameters

2021-01-17 22:45 UTC, DmitryKhodakovsky commented on src/test/resources/hw5/Cucumber_Exercise_2.feature
> +    And 6 checkboxes should be displayed on Users Table on User Table Page
The numbers of the elements should be as parameters

2021-01-17 22:45 UTC, DmitryKhodakovsky commented on src/test/resources/hw5/Cucumber_Exercise_3.feature
> +    Then 1 log row has "Vip: condition changed to true" text in log section
Number of log rows and text should be as parameter

2021-01-17 22:45 UTC, DmitryKhodakovsky commented on src/test/resources/hw5/Cucumber_Exercise_1.feature
> +    Then The site has proper Url
What is the `Proper URL` for the site?

2021-01-17 22:45 UTC, DmitryKhodakovsky commented on src/test/resources/hw5/Cucumber_Exercise_1.feature
> +    Then The site has proper title
What is the `Proper Title` for the site?

2021-01-17 22:49 UTC, OlgaPoddubnaia commented on pom.xml
> +        </dependency>
I tried to delete them for a several times but then code stops to work(all selenium annotations etc) and IntelliJ requests to load dependency so this happens.

2021-01-18 00:17 UTC, OlgaPoddubnaia commented on pom.xml
> +        </dependency>
Also I think you talk about other drivers : selenium-api, selenium-support

2021-01-18 00:25 UTC, OlgaPoddubnaia commented on src/test/java/hw5/steps/ThenStepDef.java
> +        softAssert.assertAll();
I misunderstood the example from the lecture. there is no need to use most  of softAsserts except with loops or other multiple softAsserts at one method.

2021-01-18 01:02 UTC, OlgaPoddubnaia commented on src/test/resources/hw5/Cucumber_Exercise_2.feature
> +    And I click on "User Table" button in Service dropdown
Made Service and User Table as parameters

2021-01-18 02:03 UTC, OlgaPoddubnaia commented on src/test/resources/hw5/Cucumber_Exercise_2.feature
> +    And 6 checkboxes should be displayed on Users Table on User Table Page
changed numbers to parameters (4 times)

2021-01-18 02:04 UTC, OlgaPoddubnaia commented on src/test/resources/hw5/Cucumber_Exercise_3.feature
> +    Then 1 log row has "Vip: condition changed to true" text in log section
changed number of log rows and text to parameters

2021-01-18 02:08 UTC, OlgaPoddubnaia commented on src/test/java/hw5/steps/ThenStepDef.java
> +    @Then("6 Number Type Dropdowns should be displayed on Users Table on User Table Page")
changed number to parameter

2021-01-18 02:08 UTC, OlgaPoddubnaia commented on src/test/java/hw5/steps/ThenStepDef.java
> +    @Then("6 Usernames should be displayed on Users Table on User Table Page")
changed number to parameter

2021-01-18 02:08 UTC, OlgaPoddubnaia commented on src/test/java/hw5/steps/ThenStepDef.java
> +    @Then("1 log row has \"Vip: condition changed to true\" text in log section")
changed text to parameter

2021-01-18 14:20 UTC, OlgaPoddubnaia commented on src/test/resources/hw5/Cucumber_Exercise_1.feature
> +    Then The site has proper title
made title as a parameter so the step now is "Then The site has title 'Home Page'"

2021-01-18 14:50 UTC, OlgaPoddubnaia commented on src/test/resources/hw5/Cucumber_Exercise_1.feature
> +    Then The site has proper Url
changed this step by putting url in it

2021-01-18 19:12 UTC, OlgaPoddubnaia commented on src/test/java/hw5/steps/WhenStepDef.java
> +    @When("I select water, wind checkboxes")
changed water, wind  to parameters also changed method on page object

2021-01-25 11:51 UTC, DmitryKhodakovsky approved these changes
Работа принята

2021-01-26 18:19 UTC, merged