Homework 6
OlgaPoddubnaia/OlgaPoddubnaia pull request #6
Opened 2021-01-21 18:44 UTC by OlgaPoddubnaia

2021-01-25 14:25 UTC, troe88 requested changes

2021-01-25 14:25 UTC, troe88 commented on src/main/java/hw6/dataProvider/DataProviderForJson.java
> +                        metalsAndColorsFormDataFromJson.getFromJsonObject_1().getSummary(),
This is completely prohibited to create code with reference to amount of data. What if we have to increase data set ?

2021-01-25 14:25 UTC, troe88 commented on src/main/java/hw6/entities/MetalsAndColorsFormDataFromJson.java
> +public class MetalsAndColorsFormDataFromJson {
Сurrent abstraction layer should not be care about source of this data, class needs to be renamed

2021-01-25 14:25 UTC, troe88 commented on src/main/java/hw6/pages/MetalsAndColorsPage.java
> +public class MetalsAndColorsPage extends WebPage {
Where is MetalsAndColors Form ?
Take a look at Login form and Entity Driving Testing approach from the lecture.
My expectations is: Class -> Page -> Form::submit(entity)

2021-01-28 21:24 UTC, OlgaPoddubnaia commented on src/main/java/hw6/dataProvider/DataProviderForJson.java
> +                        metalsAndColorsFormDataFromJson.getFromJsonObject_1().getSummary(),
I changed the whole dataprovider concept

2021-01-28 21:24 UTC, OlgaPoddubnaia commented on src/main/java/hw6/entities/MetalsAndColorsFormDataFromJson.java
> +public class MetalsAndColorsFormDataFromJson {
deleted this layer

2021-01-28 21:24 UTC, OlgaPoddubnaia commented on src/main/java/hw6/pages/MetalsAndColorsPage.java
> +public class MetalsAndColorsPage extends WebPage {
I made a  MetalsAndcolorsForm

2021-01-29 08:30 UTC, troe88 requested changes

2021-01-29 08:30 UTC, troe88 commented on src/main/java/hw6/forms/MetalsAndColorsForm.java
> +    public void fill(MetalsAndColors metalsAndColors) {
This method is used for FILLING form, but you are going to SUBMIT it. 
In this casem you should override submit method

2021-01-29 08:30 UTC, troe88 commented on src/main/java/hw6/pages/MetalsAndColorsPage.java
> +        MetalsAndColorsPage.checkUrl("https://jdi-testing.github.io/jdi-light/metals-colors.html");
We have Page::checkOpen() method, that allow us to perform this check.
Try it out please

2021-01-29 08:30 UTC, troe88 commented on src/test/java/hw6/tests/MetalsAndColorsTest.java
> +       fillMetalsAndColors(metalsAndColors);
Code convention issues, reformat your code please

2021-01-29 11:42 UTC, troe88 requested changes

2021-01-29 11:42 UTC, troe88 commented on src/main/java/hw6/forms/MetalsAndColorsForm.java
> +    public void fill(MetalsAndColors metalsAndColors) {
test

2021-01-29 12:04 UTC, OlgaPoddubnaia commented on src/test/java/hw6/tests/MetalsAndColorsTest.java
> +    public void isMetalsAndColorsFormFilled(String[] summary, String[] elements,
changed method name to metalsAndColorsFormTest

2021-01-29 12:05 UTC, OlgaPoddubnaia commented on src/main/java/hw6/forms/MetalsAndColorsForm.java
> +    public void fill(MetalsAndColors metalsAndColors) {
added submit method

2021-01-29 12:06 UTC, OlgaPoddubnaia commented on src/main/java/hw6/pages/MetalsAndColorsPage.java
> +        MetalsAndColorsPage.checkUrl("https://jdi-testing.github.io/jdi-light/metals-colors.html");
deleted this method and changed it on JdiSite to checkOpened()

2021-01-29 12:11 UTC, OlgaPoddubnaia commented on src/test/java/hw6/tests/MetalsAndColorsTest.java
> +       fillMetalsAndColors(metalsAndColors);
reformed code

2021-01-29 12:14 UTC, troe88 approved these changes

2021-01-29 12:23 UTC, merged